services:
  database:
    container_name: postgres
    image: postgres:15.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db-volume:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db-network
    restart: unless-stopped
  spring-boot-backend:
    container_name: spring-boot-backend
    image: michaelxsteinert/spring-boot-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/customer
    ports:
      - "8088:8080"
    networks:
      - db-network
    depends_on:
      - database
    restart: unless-stopped
networks:
  db-network:
    driver: bridge
volumes:
  db-volume: