package com.example.customer;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoInteractions;
import static org.mockito.Mockito.verifyNoMoreInteractions;
import static org.mockito.Mockito.when;

import java.io.IOException;
import java.util.Optional;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.mock.web.MockMultipartFile;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.web.multipart.MultipartFile;

import com.example.exception.DuplicateResourceException;
import com.example.exception.RequestValidationException;
import com.example.exception.ResourceNotFoundException;
import com.example.s3.S3Buckets;
import com.example.s3.S3Service;

@ExtendWith(MockitoExtension.class)
class CustomerServiceTest {

  @Mock
  private CustomerDao customerDao;
  @Mock
  private PasswordEncoder passwordEncoder;
  @Mock
  private S3Service s3Service;
  @Mock
  private S3Buckets s3Buckets;
  private CustomerService underTest;
  // No Need for Mock because it is a trivial Implementation
  private final CustomerDtoMapper customerDtoMapper = new CustomerDtoMapper();

  @BeforeEach
  void setUp() {
    underTest = new CustomerService(
        customerDao,
        passwordEncoder,
        customerDtoMapper,
        s3Service,
        s3Buckets);
  }

  @Test
  void canGetAllCustomers() {
    // When
    underTest.getAllCustomers();
    // Then
    verify(customerDao).selectAllCustomers();
  }

  @Test
  void canGetCustomer() {
    // Given
    int customerId = 0;
    Customer customer = new Customer(
        customerId,
        "Bruno",
        "bruno@mail.com",
        "password",
        14,
        Gender.MALE);
    when(customerDao.selectCustomerById(customerId)).thenReturn(Optional.of(customer));
    CustomerDto expectedCustomer = customerDtoMapper.apply(customer);
    // When
    CustomerDto actualCustomer = underTest.getCustomer(customerId);
    // Then
    assertThat(actualCustomer).isEqualTo(expectedCustomer);
  }

  @Test
  void willThrowWhenGetCustomerReturnEmptyOptional() {
    // Given
    int customerId = 0;
    when(customerDao.selectCustomerById(customerId)).thenReturn(Optional.empty());
    // When
    // Then
    assertThatThrownBy(() -> underTest.getCustomer(customerId))
        .isInstanceOf(ResourceNotFoundException.class)
        .hasMessage("Customer with ID %s not found".formatted(customerId));
  }

  @Test
  void canAddCustomer() {
    // Given
    String email = "bruno@mail.com";
    // Bad Path when Email is taken
    when(customerDao.existsCustomerWithEmail(email)).thenReturn(false);
    CustomerRegistrationRequest customerRegistrationRequest = new CustomerRegistrationRequest(
        "Bruno",
        email,
        "password",
        14,
        Gender.MALE);
    String passwordHash = "123";
    when(passwordEncoder.encode(customerRegistrationRequest.password())).thenReturn(passwordHash);
    // When
    underTest.addCustomer(customerRegistrationRequest);
    // Then
    ArgumentCaptor<Customer> customerArgumentCaptor = ArgumentCaptor.forClass(Customer.class);
    verify(customerDao).insertCustomer(customerArgumentCaptor.capture());
    Customer customerArgumentCaptorValue = customerArgumentCaptor.getValue();
    // ID is generated by the database therefore it is null
    assertThat(customerArgumentCaptorValue.getId()).isNull();
    assertThat(customerArgumentCaptorValue.getName()).isEqualTo(customerRegistrationRequest.name());
    assertThat(customerArgumentCaptorValue.getEmail()).isEqualTo(customerRegistrationRequest.email());
    assertThat(customerArgumentCaptorValue.getPassword()).isEqualTo(passwordHash);
    assertThat(customerArgumentCaptorValue.getAge()).isEqualTo(customerRegistrationRequest.age());
  }

  @Test
  void willThrowWhenAddingCustomerWhenEmailExists() {
    // Given
    String email = "bruno@mail.com";
    // Bad Path when Email is taken
    when(customerDao.existsCustomerWithEmail(email)).thenReturn(true);
    CustomerRegistrationRequest customerRegistrationRequest = new CustomerRegistrationRequest(
        "Bruno",
        email,
        "password",
        14,
        Gender.MALE);
    // When
    assertThatThrownBy(() -> underTest.addCustomer(customerRegistrationRequest))
        .isInstanceOf(DuplicateResourceException.class)
        .hasMessage("Email %s already exists".formatted(email));
    // Then
    verify(customerDao, never()).insertCustomer(any());
  }

  @Test
  void canUpdateCustomer() {
    // Given
    int customerId = 10;
    Customer customer = new Customer(
        customerId,
        "Bruno",
        "bruno@mail.com",
        "password",
        14,
        Gender.MALE);
    when(customerDao.selectCustomerById(customerId)).thenReturn(Optional.of(customer));
    String newEmail = "bruns@mail.com";
    CustomerUpdateRequest customerUpdateRequest = new CustomerUpdateRequest("Bruns", newEmail, "password", 15,
        Gender.MALE);
    when(customerDao.existsCustomerWithEmail(newEmail)).thenReturn(false);
    // When
    underTest.updateCustomer(customerId, customerUpdateRequest);
    // Then
    ArgumentCaptor<Customer> customerArgumentCaptor = ArgumentCaptor.forClass(Customer.class);
    verify(customerDao).updateCustomer(customerArgumentCaptor.capture());
    Customer capturedCustomer = customerArgumentCaptor.getValue();
    assertThat(capturedCustomer.getName()).isEqualTo(customerUpdateRequest.name());
    assertThat(capturedCustomer.getEmail()).isEqualTo(customerUpdateRequest.email());
    assertThat(capturedCustomer.getAge()).isEqualTo(customerUpdateRequest.age());
  }

  @Test
  void willThrowWhenTryingToUpdateCustomerEmailWhenAlreadyTaken() {
    // Given
    int customerId = 10;
    Customer customer = new Customer(
        customerId,
        "Bruno",
        "bruno@mail.com",
        "password",
        14,
        Gender.MALE);
    when(customerDao.selectCustomerById(customerId)).thenReturn(Optional.of(customer));
    String newEmail = "bruns@mail.com";
    CustomerUpdateRequest updateRequest = new CustomerUpdateRequest(null, newEmail, null, null, null);
    when(customerDao.existsCustomerWithEmail(newEmail)).thenReturn(true);
    // When
    assertThatThrownBy(() -> underTest.updateCustomer(customerId, updateRequest))
        .isInstanceOf(DuplicateResourceException.class)
        .hasMessage("Email already exists");
    // Then
    verify(customerDao, never()).updateCustomer(any());
  }

  @Test
  void willThrowWhenCustomerUpdateHasNoChanges() {
    // Given
    int customerId = 10;
    Customer customer = new Customer(
        customerId,
        "Bruno",
        "bruno@mail.com",
        "password",
        14,
        Gender.MALE);
    when(customerDao.selectCustomerById(customerId)).thenReturn(Optional.of(customer));
    CustomerUpdateRequest customerUpdateRequest = new CustomerUpdateRequest(
        customer.getName(),
        customer.getEmail(),
        customer.getPassword(),
        customer.getAge(),
        customer.getGender());
    // When
    assertThatThrownBy(() -> underTest.updateCustomer(customerId, customerUpdateRequest))
        .isInstanceOf(RequestValidationException.class)
        .hasMessage("No Customer Data Changes found");
    // Then
    verify(customerDao, never()).updateCustomer(any());
  }

  @Test
  void canRemoveCustomer() {
    // Given
    int customerId = 10;
    when(customerDao.existsCustomerWithId(customerId)).thenReturn(true);
    // When
    underTest.removeCustomer(customerId);
    // Then
    verify(customerDao).removeCustomer(customerId);
  }

  @Test
  void willThrowRemoveCustomerByIdNotExists() {
    // Given
    int customerId = 10;
    when(customerDao.existsCustomerWithId(customerId)).thenReturn(false);
    // When
    assertThatThrownBy(() -> underTest.removeCustomer(customerId))
        .isInstanceOf(ResourceNotFoundException.class)
        .hasMessage("Customer with ID %s not found".formatted(customerId));
    // Then
    verify(customerDao, never()).removeCustomer(customerId);
  }

  @Test
  void canUploadCustomerImage() {
    // Given
    int customerId = 10;
    when(customerDao.existsCustomerWithId(customerId)).thenReturn(true);
    byte[] file = "Bruno".getBytes();
    MultipartFile multipartFile = new MockMultipartFile("file", file);
    String bucketName = "my-bucket";
    when(s3Buckets.getCustomerBucket()).thenReturn(bucketName);
    // When
    underTest.uploadCustomerImage(customerId, multipartFile);
    // Then
    ArgumentCaptor<String> customerImageIdArgumentCaptor = ArgumentCaptor.forClass(String.class);
    // eq() ensures that the correct `customerId` is being passed to Method Call
    verify(customerDao).updateCustomerImageId(customerImageIdArgumentCaptor.capture(), eq(customerId));
    verify(s3Service).putObject(
        bucketName,
        "images/%s/%s".formatted(customerId, customerImageIdArgumentCaptor.getValue()),
        file);
  }

  @Test
  void canNotUploadCustomerImageWhenCustomerDoesNotExist() {
    // Given
    int customerId = 10;
    when(customerDao.existsCustomerWithId(customerId)).thenReturn(false);
    // When
    assertThatThrownBy(() -> {
      underTest.uploadCustomerImage(customerId, mock(MultipartFile.class));
    }).isInstanceOf(ResourceNotFoundException.class)
        .hasMessage("Customer with ID %s not found".formatted(customerId));
    // Then
    verify(customerDao).existsCustomerWithId(customerId);
    verifyNoMoreInteractions(customerDao);
    verifyNoInteractions(s3Buckets);
    verifyNoInteractions(s3Service);
  }

  @Test
  void canNotUploadCustomerImageWhenExceptionThrown() throws IOException {
    // Given
    int customerId = 10;
    when(customerDao.existsCustomerWithId(customerId)).thenReturn(true);
    MultipartFile multipartFile = mock(MultipartFile.class);
    when(multipartFile.getBytes()).thenThrow(IOException.class);
    String bucketName = "my-bucket";
    when(s3Buckets.getCustomerBucket()).thenReturn(bucketName);
    // When
    assertThatThrownBy(() -> {
      underTest.uploadCustomerImage(customerId, multipartFile);
    }).isInstanceOf(RuntimeException.class)
        .hasMessage("Failed to upload Customer Image")
        .hasRootCauseInstanceOf(IOException.class);
    // Then
    verify(customerDao, never()).updateCustomerImageId(anyString(), any());
  }

  @Test
  void downloadUploadCustomerImage() {
    // Given
    int customerId = 10;
    String imageId = "imageId";
    Customer customer = new Customer(
        customerId,
        "Bruno",
        "bruno@mail.com",
        "password",
        14,
        Gender.MALE,
        imageId);
    when(customerDao.selectCustomerById(customerId)).thenReturn(Optional.of(customer));
    String bucketName = "my-bucket";
    when(s3Buckets.getCustomerBucket()).thenReturn(bucketName);
    byte[] file = "Bruno".getBytes();
    when(s3Service.getObject(bucketName, "images/%s/%s".formatted(customerId, imageId)))
        .thenReturn(file);
    // When
    byte[] actualCustomerImage = underTest.downloadCustomerImage(customerId);
    // Then
    assertThat(actualCustomerImage).isEqualTo(file);
  }

  @Test
  void canNotDownloadCustomerImageWhenNotImageIdExists() {
    // Given
    int customerId = 10;
    String imageId = null;
    Customer customer = new Customer(
        customerId,
        "Bruno",
        "bruno@mail.com",
        "password",
        14,
        Gender.MALE);
    when(customerDao.selectCustomerById(customerId)).thenReturn(Optional.of(customer));
    // When
    // Then
    assertThatThrownBy(() -> {
      underTest.downloadCustomerImage(customerId);
    }).isInstanceOf(ResourceNotFoundException.class)
        .hasMessage("Image ID %s not found".formatted(imageId));
    verifyNoInteractions(s3Service);
    verifyNoInteractions(s3Buckets);
  }

  @Test
  void canNotDownloadCustomerImageWhenCustomerNotExists() {
    // Given
    int customerId = 10;
    when(customerDao.selectCustomerById(customerId)).thenReturn(Optional.empty());
    // When
    // Then
    assertThatThrownBy(() -> {
      underTest.downloadCustomerImage(customerId);
    }).isInstanceOf(ResourceNotFoundException.class)
        .hasMessage("Customer with ID %s not found".formatted(customerId));
    verifyNoInteractions(s3Service);
    verifyNoInteractions(s3Buckets);
  }
}